### ISSUE TITLE
Server side collections for reactive D3

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [nate-strauser/meteor-cookbook#2]
Hi @nate-strauser 

I'm trying to get the reactive d3 components you wrote to work on server side [in my project](https://github.com/keyvan-m-sadeghi/python-d3-meteor/blob/reviz-v-0.6.1/meteor/d3-example/client/pie/pieChart.js#L6), so I've initiated the collection as a global in the `lib` folder and copy and pasted your code to `onReady` hook. This results in a blank svg tag, could you please advise, what am I doing wrong?

Cheers,
Keyvan

**Comment by nate-strauser** [comment]
you should not have to use the onready hook - try to just define you events and helpers outside of the subscribe call and let me know what you get

**Comment by keyvan-m-sadeghi** [comment]
Hi nate,

Thanks for your timely reply, unfortunately that still didn't resolve the issue, but to my surprise [a similar approach](http://stackoverflow.com/questions/25227732/meteor-deps-autorun-know-when-data-has-been-fully-fetched) worked.

Thanks again for your help. In the meantime our requirements have changed and I need to Implement Observe for D3's basic charts. Will use your other tutorial.

Cheers,
K
